### ISSUE TITLE
Grails version

### ISSUE THREAD

**Issue by mobilars** [silverbullet-dk/opentele-server#1]
README-file says Grails-version 2.1.0, but the application properties says 2.4.4. It seems the correct is 2.4.4?

**Comment by ErikMejerHansen** [comment]
The correct version is 2.4.4. 
Please be aware that there's an issue with the bootatrapping of data that prevents the server from starting.  I'll push a fix tomorrow (and update the README-file)

**Comment by ErikMejerHansen** [comment]
Fixed in: a9b1b3dcc99d0b5181958db5584b2d1c66ea6243
